export enum Entity {
  application = 'application',
  blog = 'blog',
  coupon = 'coupon',
  cms_block = 'cms_block',
  cms_page = 'cms_page',
  testament = 'inheritance',
  master_data_asset_type = 'master_data_asset_type',
  master_data_product = 'master_data_product',
  master_data_prefix = 'master_data_prefix',
  master_data_relation = 'master_data_relation',
  package = 'package',
  payment = 'payment',
  survey = 'survey',
  survey_answer = 'survey_answer',
  user = 'user',
}